language: cpp

env:
  global:
    - secure: "RGQHmyTeJyT08JV6w9k9QJQSt+EtHGH1i56vwdU6+QrnkUPXqUMYYHvyKjOHYOu1dEKBryqHEl4fQSJwl0VNDKI52ehgzP5ilM6JoWg/zTKic5XjXSIveWG0mnVfc4d4s8Fv3gkPnnqcGbDN3kIkAeiRockpfLWZI3zCPZduDH4="
  matrix:
    - COMPILER=g++-4.9
      COMPILER_PACKAGE=g++-4.9

    - COMPILER=g++-4.8
      COMPILER_PACKAGE=g++-4.8

    - COMPILER=g++-4.7
      COMPILER_PACKAGE=g++-4.7

    - COMPILER=clang++-3.5
      COMPILER_PACKAGE=clang-3.5

    - COMPILER=clang++-3.6
      COMPILER_PACKAGE=clang-3.6

before_install:
 - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
 - sudo add-apt-repository ppa:boost-latest/ppa -y
 - sudo add-apt-repository ppa:h-rayflood/llvm-upper -y
 - sudo apt-get update -qq
 - sudo apt-get install -qq libboost1.54-dev libboost-program-options1.54-dev build-essential ${COMPILER_PACKAGE}
 - ${COMPILER} --version
 - wget http://www.cmake.org/files/v3.2/cmake-3.2.2.tar.gz
 - tar xf cmake-3.2.2.tar.gz
 - cd cmake-3.2.2
 - ./configure
 - make
 - sudo make install
 - cd ..

before_script:
 - export CXX=${COMPILER}
 - mkdir build
 - cd build
 - cmake -DWITH_UNIT_TESTS=ON ..

script: make

after_script: make test

addons:
  coverity_scan:
    project:
      name: "no1msd/mstch"
      description: "Build submitted via Travis CI"
    notification_email: no1msd@gmail.com
    build_command_prepend: "cmake -DWITH_UNIT_TESTS=ON ."
    build_command:   "make -j 4"
    branch_pattern: coverity_scan