language: cpp
sudo: false

matrix:
  include:
    - env:
        - COMPILER=g++-4.9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - boost-latest
            - george-edison55-precise-backports
          packages:
            - g++-4.9
            - cmake
            - cmake-data
            - libboost1.55-dev
            - libboost-regex1.55-dev
            - libboost-program-options1.55-dev
    - env:
        - COMPILER=g++-4.8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - boost-latest
            - george-edison55-precise-backports
          packages:
            - g++-4.8
            - cmake
            - cmake-data
            - libboost1.55-dev
            - libboost-regex1.55-dev
            - libboost-program-options1.55-dev
    - env:
        - COMPILER=g++-4.7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - boost-latest
            - george-edison55-precise-backports
          packages:
            - g++-4.7
            - cmake
            - cmake-data
            - libboost1.55-dev
            - libboost-regex1.55-dev
            - libboost-program-options1.55-dev
    - env:
        - COMPILER=clang++-3.5
      addons:
        apt:
          sources:
            - llvm-toolchain-precise-3.5
            - boost-latest
            - george-edison55-precise-backports
          packages:
            - clang-3.5
            - cmake
            - cmake-data
            - libboost1.55-dev
            - libboost-regex1.55-dev
            - libboost-program-options1.55-dev
    - env:
        - COMPILER=clang++-3.6
      addons:
        apt:
          sources:
            - llvm-toolchain-precise-3.6
            - boost-latest
            - george-edison55-precise-backports
          packages:
            - clang-3.6
            - cmake
            - cmake-data
            - libboost1.55-dev
            - libboost-regex1.55-dev
            - libboost-program-options1.55-dev

before_script:
 - export CXX=${COMPILER}
 - mkdir build
 - cd build
 - cmake -DWITH_UNIT_TESTS=ON ..

script: make

after_script: make test
