language: cpp

env:
  matrix:
    - CXX=g++-4.9
    - CXX=g++-4.8
    - CXX=g++-4.7

before_install:
 - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
 - sudo add-apt-repository ppa:boost-latest/ppa -y
 - sudo apt-get update -qq
 - sudo apt-get install -qq cmake libboost1.54-dev libboost-program-options1.54-dev ${CXX}

before_script:
 - mkdir build
 - cd build
 - cmake -DWITH_UNIT_TESTS=ON ..

script: make

after_script: make test
