language: cpp
sudo: false

matrix:
  include:
    - env: COMPILER=g++-4.9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
    - env: COMPILER=g++-4.8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8
    - env: COMPILER=g++-4.7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.7
    - env: COMPILER=clang++-3.5
      addons:
        apt:
          sources:
            - llvm-toolchain-precise-3.5
          packages:
            - clang-3.5
    - env: COMPILER=clang++-3.6
      addons:
        apt:
          sources:
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6

addons:
  apt:
    sources:
     - boost-latest
     - george-edison55-precise-backports
    packages:
     - cmake
     - cmake-data
     - libboost1.55-dev
     - libboost-regex1.55-dev
     - libboost-program-options1.55-dev

before_script:
 - export CXX=${COMPILER}
 - mkdir build
 - cd build
 - cmake -DWITH_UNIT_TESTS=ON ..

script: make

after_script: make test
