environment:
  matrix:
    - GENERATOR: "Visual Studio 12"
      CONFIG: Debug

build_script:
  - mkdir build
  - cd build
  - cmake "-G%GENERATOR%" -DBOOST_ROOT="C:\Libraries\boost_1_59_0" ..
  - cmake --build . --config "%CONFIG%"
