environment:
  matrix:
    - GENERATOR: "Visual Studio 12"
      CONFIG: Debug

build_script:
  - mkdir build
  - cd build
  - cmake "-G%GENERATOR%" -DBOOST_ROOT="C:\Libraries\boost_1_59_0" -DBOOST_LIBRARYDIR="c:\Libraries\boost_1_59_0\stage\lib" -DWITH_UNIT_TESTS=ON ..
  - cmake --build . --config "%CONFIG%"
