environment:
  matrix:
    - GENERATOR: "Visual Studio 12"
      CONFIG: Debug

install:
  - git submodule init
  - git submodule update

build_script:
  - mkdir build
  - cd build
  - cmake "-G%GENERATOR%" -DBOOST_ROOT="C:\Libraries\boost" -DBOOST_LIBRARYDIR="c:\Libraries\boost\stage\lib" -DBoost_USE_STATIC_LIBS=ON -DWITH_UNIT_TESTS=ON ..
  - cmake --build . --config "%CONFIG%"

test_script:
  - ctest
